---
- name: Establecer el httpd y abrir el puerto del firewall
  hosts: wordpress

  tasks:
  - name: Instalar paquete apache
    yum:
     name: httpd
     state: present

  - name: Iniciar httpd
    service:
     name: httpd
     state: started

  - name: Abrir puerto para servicio http
    firewalld:
     service: http
     permanent: true
     state: enabled

  - name: Reiniciar servicio firewalld y cargar los cambios del firewall
    service:
     name: firewalld
     state: reloaded
   
  - name: Descargar y descomprimir WordPress
    get_url:
     url: https://wordpress.org/latest.tar.gz
     dest: /tmp/wordpress.tar.gz
     mode: '0644'

  - name: Descomprimir archivo de WordPress
    become: yes
    unarchive:
     src: /tmp/wordpress.tar.gz
     dest: /var/www/html
     remote_src: yes

  - name: Configurar archivo wp-config.php
    become: yes
    template:
     src: /etc/ansible/recursos/wp-config.php
     dest: /var/www/html/wordpress/wp-config.php
     mode: '0644'

  - name: Establecer permisos para archivos de WordPress
    become: yes
    file:
     path: /var/www/html/wordpress/
     state: directory
     mode: '0755'
     recurse: yes
     #     become: yes
     #     file:
     #    path: /var/www/html/wordpress/wp-content/
     #    state: directory
     #    mode: '0755'
     #    recurse: yes
     #     become: yes
     #     file:
     #     path: /var/www/html/wordpress/wp-content/uploads/
     #     state: directory
     #     mode: '0775'
     #     recurse: yes

  - name: Actualizar configuración de Apache y reiniciar servicio
    become: yes
    template:
     src: /etc/ansible/recursos/wp-config.php
     dest: /etc/httpd/conf.d/wordpress.conf
     mode: '0644'
#     service:
#             name: httpd
#             state: restart

  - name: Instalar módulos de PHP requeridos
    yum:
     name:
      - php
      - php-mysqlnd
      - php-fpm
      - php-gd
      - php-xml
      - php-mbstring
      - php-json
      - php-bcmath
      - php-curl
     state: present

  - name: Reiniciar apache
    service: 
     name: httpd
     state: restarted
