---
- name: Instalar paquete http y configurar el Proxy
  hosts: httpd
  roles:
          - UpdateRepo
          - httpInstall
          - ProxyConfig

- name: Instalar y configurar Wordpress para que conecte con la base de datos
  hosts: wordpress
  roles:
          - UpdateRepo
          - httpInstall
          - wordpressInstall

- name: Instalación y creación de tabla y usuario en MariaDB para Wordpress
  hosts: mariadb
  roles:
          - UpdateRepo
          - mariadbInstall
          - mariadbRecovery
