---
- name: Instalar WordPress
  hosts: 192.168.10.61
  become: true

  tasks:
  - name: Actualizar caché de los paquetes CentOS
    yum:
      name: '*'
      state: latest
      update_cache: true

  - name: Instalar paquetes requeridos
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - httpd
      - php
      - php-gd
      - php-xml
      - php-mbstring
      - php-mysqli

  - name: Abrir puerto para servicio http
    firewalld:
     service: http
     permanent: true
     state: enabled

  - name: Reiniciar servicio firewalld y cargar los cambios del firewall
    service:
     name: firewalld
     state: reloaded

  - name: Iniciar Apache web server
    service:
      name: httpd
      state: started
      enabled: true

  - name: Copiar ficheros de WordPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
      owner: apache
      group: apache
      mode: '0755'

  - name: Establecer configuración WordPress
    template:
      src: /etc/ansible/recursos/wp-config.php
      dest: /var/www/html/wordpress/wp-config.php
      owner: apache
      group: apache
      mode: '0644'

  - name: Reiniciar Apache web server
    service:
      name: httpd
      state: restarted

