---
- name: Instalar y configurar Apache, PHP y WordPress en CentOS 8
  hosts: wordpress
  become: yes

  tasks:
    - name: Actualizar caché de paquetes
      yum:
        update_cache: yes

    - name: Instalar Apache
      yum:
        name: httpd
        state: latest

    - name: Iniciar servicio de Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Instalar módulos PHP necesarios
      yum:
        name:
          - php
          - php-mysqlnd
          - php-fpm
          - php-gd
          - php-xml
          - php-json
          - php-opcache
        state: latest

    - name: Descargar y descomprimir WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Descomprimir WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        creates: /var/www/html/wordpress

    - name: Asignar permisos de usuario y grupo a la carpeta de WordPress
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: apache
        group: apache
        recurse: yes
        mode: '0755'

    - name: Copiar archivo de configuración de WordPress
      template:
        src: ../recursos/wp-config.php
        dest: /var/www/html/wordpress/wp-config.php
        owner: apache
        group: apache
        mode: '0644'

    - name: Reiniciar servicio de Apache
      systemd:
        name: httpd
        state: restarted

